/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Adevanced: typeof import('./../components/miniComponents/Adevanced.vue')['default']
    Content: typeof import('./../components/Content.vue')['default']
    DataList: typeof import('./../components/miniComponents/DataList.vue')['default']
    DefaultLayout: typeof import('./../layouts/DefaultLayout.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Nav: typeof import('./../components/Nav.vue')['default']
    RightBar: typeof import('./../components/RightBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../components/Sidebar.vue')['default']
    SliderButton: typeof import('./../components/miniComponents/SliderButton.vue')['default']
    SportLight: typeof import('./../components/SportLight.vue')['default']
    TableView: typeof import('./../components/miniComponents/TableView.vue')['default']
    TakeProfit: typeof import('./../components/miniComponents/TakeProfit.vue')['default']
    Tracking1: typeof import('./../components/Tracking1.vue')['default']
    Tracking4: typeof import('./../components/Tracking4.vue')['default']
    TrackingView: typeof import('./../components/TrackingView.vue')['default']
    TView: typeof import('./../components/miniComponents/TView.vue')['default']
  }
}
